---
- name: Setup Loki
  hosts: loki
  roles:
    - role: docker
      become: true
    - role: traefik
      tags: traefik
    - role: plex
      tags: plex
    - role: arr
      tags: arr
    - role: portainer
      tags: portainer
    - role: uptime_kuma
      tags: uptime_kuma
    - role: karakeep
      tags: karakeep

- name: Setup Cherrypi
  hosts: cherrypi
  roles:
    - role: docker
      become: true
    - role: traefik
      tags: traefik
    - role: portainer
      tags: portainer
