services:
  web:
    image: ghcr.io/karakeep-app/karakeep:${KARAKEEP_VERSION:-release}
    restart: unless-stopped
    volumes:
      # By default, the data is stored in a docker volume called "data".
      # If you want to mount a custom directory, change the volume mapping to:
      # - /path/to/your/directory:/data
      - ./data:/data
    networks:
      proxy:
      default:
    env_file:
      - .env
    labels:
      traefik.enable: "true"
      traefik.docker.network: "proxy"
      traefik.http.routers.karakeep.rule: "Host(`karakeep.{{ inventory_hostname }}.{{ domain }}`)"
      traefik.http.services.karakeep.loadbalancer.server.port: "3000"
  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:latest
    restart: unless-stopped
    networks:
      default:
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
  meilisearch:
    image: getmeili/meilisearch:v1.13.3
    restart: unless-stopped
    networks:
      default:
    env_file:
      - .env
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - meilisearch:/meili_data

networks:
  proxy:
    external: true

volumes:
  meilisearch:
