---
- name: Create komodo folder
  ansible.builtin.file:
    path: "{{ deploy_path }}/komodo"
    state: directory

- name: Copy files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop: "{{ komodo_files }}"
  vars:
    komodo_files:
      - src: compose.yml
        dest: "{{ deploy_path }}/komodo/compose.yml"
      - src: env.j2
        dest: "{{ deploy_path }}/komodo/.env"

- name: Start komodo
  community.docker.docker_compose_v2:
    project_src: "{{ deploy_path }}/komodo"
  become: true
  register: komodo_output

- name: Show results
  ansible.builtin.debug:
    var: komodo_output

