services:
  portainer_agent:
    container_name: portainer-agent
    image: portainer/agent
    restart: unless-stopped
    networks:
      default:
    ports:
      - 9001:9001
    security_opt:
      - no-new-privileges:true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes


  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    command: "--admin-password='{{ portainer.password }}'"
    networks:
      proxy:
      default:
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      traefik.enable: "true"
      traefik.docker.network: "proxy"
      traefik.http.services.portainer.loadbalancer.server.port: "9000"
      traefik.http.routers.portainer.rule: "Host(`portainer.{{ domain }}`) || Host(`portainer.{{ inventory_hostname }}.{{ domain }}`)"

networks:
  proxy:
    external: true

volumes:
  portainer_data:
    name: portainer_data
