---
- name: Create uptime-kuma folder
  ansible.builtin.file:
    path: "{{ deploy_path }}/uptime-kuma/data"
    state: directory

- name: Copy compose file
  ansible.builtin.template:
    src: compose.yml
    dest: "{{ deploy_path }}/uptime-kuma/compose.yml"

- name: Start uptime-kuma
  community.docker.docker_compose_v2:
    project_src: "{{ deploy_path }}/uptime-kuma"
  become: true
  register: uptimekuma_output

- name: Show results
  ansible.builtin.debug:
    var: uptimekuma_output
