services:
  adguard:
    image: adguard/adguardhome:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      proxy:
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 127.0.0.1:3000:3000
    volumes:
      - data:/opt/adguardhome/work
      - ./conf:/opt/adguardhome/conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.adguard.loadbalancer.server.port=80"
      - "traefik.http.routers.adguard.rule=Host(`adguard.{{ inventory_hostname }}.{{ domain }}`)"

networks:
  proxy:
    external: true
volumes:
  data:
