---
- name: Create proxy network
  community.docker.docker_network:
    name: proxy
    state: present
  become: true

- name: Create traefik folders
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ deploy_path }}/traefik/data"
    - "{{ deploy_path }}/traefik/dynamic"

- name: Copy files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0600'
  loop: "{{ traefik_files }}"
  vars:
    traefik_files:
      - src: compose.yml.j2
        dest: "{{ deploy_path }}/traefik/compose.yml"
      - src: env.j2
        dest: "{{ deploy_path }}/traefik/.env"

- name: Copy cf-token
  ansible.builtin.template:
    src: cf-token.j2
    dest: "{{ deploy_path }}/traefik/cf-token"
    mode: '0600'

- name: Copy traefik.yml
  ansible.builtin.template:
    src: traefik.yml.j2
    dest: "{{ deploy_path }}/traefik/data/traefik.yml"
    mode: '0644'
  register: traefik_config

- name: Copy dynamic.yml
  ansible.builtin.template:
    src: dynamic.yml.j2
    dest: "{{ deploy_path }}/traefik/dynamic/dynamic.yml"
    mode: '0644'
  register: traefik_dynamic_config

- name: Ensure acme.json exists with correct permissions
  ansible.builtin.file:
    path: "{{ deploy_path }}/traefik/data/acme.json"
    state: touch
    mode: '0600'
    modification_time: preserve
    access_time: preserve

- name: Start traefik
  community.docker.docker_compose_v2:
    project_src: "{{ deploy_path }}/traefik"
    recreate: "{{ 'always' if (traefik_config.changed or traefik_dynamic_config.changed) else 'auto' }}"
  become: true
  register: traefik_output

- name: Show results
  ansible.builtin.debug:
    var: traefik_output
